# ============================================================
# comparison_charts.py
# Charts   : Column Chart, Bar Chart,
#            Stacked Column, Stacked Bar,
#            Clustered Column, Clustered Bar
# ============================================================

# Member 2 — add your functions here
# Each function should return a Plotly go.Figure
# Example:
#   def make_column_chart(df): ...
#   def make_bar_chart(df): ...
#   def make_stacked_column(df): ...
#   def make_stacked_bar(df): ...
#   def make_clustered_column(df): ...
#   def make_clustered_bar(df): ...